### ISSUE TITLE
s3_band_extract "cloud over snow"

### ISSUE THREAD

**Issue by jasonebox** [maximlamare/S3_extract#7]
Dear Maxim,

Idepix "cloud over snow" output appears to be working in SNAP 7.0 :-)

Can it be added to s3_band_extract.py?

For plugins, I have Idepix OLCI for S3 Snow v0.82 and O2 correction v0.81 available from the same old BC ftp... In SNAP, one needs a DEM, which is available in the same old BC ftp data folder

here is a ss of how the DEM is an input
![image](https://user-images.githubusercontent.com/32133350/69729892-67bc1e80-1127-11ea-8591-e7ecac359530.png)

here is the menu selection
![image](https://user-images.githubusercontent.com/32133350/69729729-2297ec80-1127-11ea-96a8-550bd43a55f8.png)

got a chance to look into this?

best,

Jason

**Comment by BaptisteVandecrux** [comment]
I don't know if this issue has been solved since I can see that S3_extract_snow_products.py is supposed to output an "autocloud" variable from Idepix.
However that part of the script fails when I try to run S3_extract_snow_products.py:
```
INFO: org.hsqldb.persist.Logger: dataFileCache open start
Traceback (most recent call last):
  File "s3_extract_snow_products.py", line 403, in <module>
    input_args.platform,
  File "s3_extract_snow_products.py", line 157, in main
    output_errorfile,
  File "/home/bav/S3_extract/snappy_funcs.py", line 588, in getS3values
    prod_subset, pix_coords[0], pix_coords[1]
  File "/home/bav/S3_extract/snappy_funcs.py", line 309, in idepix_cloud
    "Snap.Idepix.Olci.S3Snow", parameters, in_prod
RuntimeError: org.esa.snap.core.gpf.OperatorException: Unknown operator 'Snap.Idepix.Olci.S3Snow'. Is the name correctly spelled?
```

I have tried with both plugins idepix-olci-s3snow-1.0.nbm and idepix-olci-s3snow-0.82-SNAPSHOT.nbm. None of them seem to have the operator.

Here are the modules I have:
```
(SNAP) bav@geussnow01:~/S3_extract$ snap --nosplash --nogui --modules --list --refresh|grep idepix
org.esa.snap.idepix.olci.s3snow                    0.82     Enabled
org.esa.s3tbx.s3tbx.idepix                         7.0.0.0  Enabled
org.esa.s2tbx.s2tbx.s2msi.idepix                   7.0.0.0  Installed
org.esa.s3tbx.s3tbx.idepix.ui                      7.0.0.0  Enabled
org.esa.s2tbx.s2tbx.s2msi.idepix.ui                7.0.0.0  Installed
```
I guess we need to relocate the latest operator for Idepix and cloud_over_snow variable.
This is low priority so I have modified my version to not use idepix at all.
